# Generated by Django 4.1.6 on 2023-02-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-id'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
    ]
